// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Voia.Api.Data;

#nullable disable

namespace Voia.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251113_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // Note: This snapshot includes only the index creation changes
            // The full model is maintained by EF Core migrations system
#pragma warning restore 612, 618
        }
    }
}
